### ISSUE TITLE
Naming tables

### ISSUE THREAD

**Issue by brcnitk** [Shivyoddha/Telephone-Directory-Web#9]
![Screenshot (9)](https://github.com/Shivyoddha/Telephone-Directory-Web/assets/23404824/9ea7ea0c-56b4-41d4-86e9-ef2694523704)

Can we name (if possible) the tables as: Departments --> Sections, NITK Staffs --> All_Data, Sections --> Units.

**Comment by Shivyoddha** [comment]
Issue #9 resolved
